Collections: HashTable, LinkedList and Queue
galvisma/Algorithms pull request #4
Opened 2023-04-07 21:52 UTC by galvisma

This PR contains examples of the basic instructions to create, add, delete and display the content of a Hashtable, LinkedList and Queue.

2023-04-09 15:23 UTC, julianespinel requested changes
A few comments.

Please remove all the files `*.class`, and add the folder `out/` to the file `.gitignore` to avoid uploading these files in the future.

2023-04-09 15:23 UTC, julianespinel commented on src/hashTable/Main.java
> +    }
This is correct, however, there is an easier way to do this:

```java
    private static void readingTablaHash(Hashtable<Integer, String> table) {
        Set<Integer> keys = table.keySet();
        for (Integer key : keys) {
            System.out.println("key: " + key + " " +"Name: " + table.get(key));
        }
    }
```

2023-04-09 15:23 UTC, julianespinel commented on src/queueList/Main.java
> +}
Please avoid using UI components in these exercises. Use the terminal instead.

In this queue exercise, the idea is to use the methods `add` and `remove` to see how a queue is a FIFO (First In First Out) data structure.

See:
* https://en.wikipedia.org/wiki/Queue_(abstract_data_type)
* https://docs.oracle.com/javase/8/docs/api/java/util/Queue.html

2023-04-09 15:23 UTC, julianespinel commented on src/queueList/Queue.java
> +}
Please avoid using UI components in these exercises. Use the terminal instead.

For this task, you don't have to create the `Queue` yourself.
The idea is to use the class Queue from Java. See: https://docs.oracle.com/javase/8/docs/api/java/util/Queue.html

2023-04-18 00:50 UTC, galvisma commented
This PR is closed in favor of last version collections

2023-04-18 00:50 UTC, closed without merging